// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhxxhknykomsmwltmzjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoeHhoa255a29tc213bHRtemp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNDg5MTcsImV4cCI6MjA3MDcyNDkxN30.lBa1IHuUprTpR7KTt6u6msMbsOI-S0J4C2xrZiVS4Js";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});